order_acc = "0xd41bee801ff19b97ecfa3a176b6bd4906c474b87753a4a39a2e696a410fa6e1"
cancel_acc = "0x0"
order_count = 1
cancel_count = 0
fills_root = "0x1972f4cc05a05d5e3210be942bf1de41a51a73dde981c43a3243f2cb856b2a9d"
active_pool_count = 1
active_pool_clearings = [
  { pool_id = 0, clearing_price = "99999996656636576395", token_lo = "0x2f295ee5dff385343675815acec5e3cbd21c64d37062e3186eec10ee983f5a73", token_hi = "0x2365f7da7668d8471b387f2a6946359cd431d3ed6f5af5cf227b4d26f6277a50", swap = { a_to_pool = "0", b_to_pool = "299099", a_from_pool = "29909879", b_from_pool = "0", current_sqrt_price_after = "100000000000498498", pool_state_commitment = "3080803795085238833595941299394721177429202402608382594289818447054003013436", active_bucket_count = 1, active_bucket_deltas = [{ bucket_id = 0, reserve_a_add = "0", reserve_a_sub = "29909879", reserve_b_add = "299099", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "1500" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }] } },
  { pool_id = 4294967295, clearing_price = "0", token_lo = "0x0", token_hi = "0x0", swap = { a_to_pool = "0", b_to_pool = "0", a_from_pool = "0", b_from_pool = "0", current_sqrt_price_after = "0", pool_state_commitment = "0", active_bucket_count = 0, active_bucket_deltas = [{ bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }] } },
  { pool_id = 4294967295, clearing_price = "0", token_lo = "0x0", token_hi = "0x0", swap = { a_to_pool = "0", b_to_pool = "0", a_from_pool = "0", b_from_pool = "0", current_sqrt_price_after = "0", pool_state_commitment = "0", active_bucket_count = 0, active_bucket_deltas = [{ bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }, { bucket_id = 65535, reserve_a_add = "0", reserve_a_sub = "0", reserve_b_add = "0", reserve_b_sub = "0", cum_fee_a_per_share_increment = "0", cum_fee_b_per_share_increment = "0" }] } },
]
orders = [
  { side = true, amount_in = "300000", limit_price = "1000000000000000", order_nonce = "0x396d7284910c7fe4d391a7f2cc2b7608670222e03e733b0517524512e06423", submitted_at_block = 124760, owner = "0x1796882484cb4c743885d4a6b40b755709f64e22e7cdcbbda17e7520510cfb33", path_len = 2, path = ["0x2f295ee5dff385343675815acec5e3cbd21c64d37062e3186eec10ee983f5a73", "0x2365f7da7668d8471b387f2a6946359cd431d3ed6f5af5cf227b4d26f6277a50", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
  { side = false, amount_in = "0", limit_price = "0", order_nonce = "0x0", submitted_at_block = 0, owner = "0x0", path_len = 2, path = ["0x0", "0x0", "0x0"] },
]
cancelled_indices = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
fills = [
  { order_nonce = "0x396d7284910c7fe4d391a7f2cc2b7608670222e03e733b0517524512e06423", hop_index = 0, amount_out = "29909879", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
  { order_nonce = "0x0", hop_index = 0, amount_out = "0", pool_id = 0 },
]
fills_len = 1
fill_to_order_index = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
pool_bucket_states_before = [
  [
      { reserve_a = "2000000000000000000", reserve_b = "0", liquidity = "600000000000000000", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
  ],
  [
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
  ],
  [
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
  ],
]
pool_bucket_states_after = [
  [
      { reserve_a = "1999999999970090121", reserve_b = "299099", liquidity = "600000000000000000", cum_fee_a_per_share = "0", cum_fee_b_per_share = "1500" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
  ],
  [
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
  ],
  [
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
      { reserve_a = "0", reserve_b = "0", liquidity = "0", cum_fee_a_per_share = "0", cum_fee_b_per_share = "0" },
  ],
]
pool_sqrt_p_before = [
  "100000000000000000",
  "0",
  "0",
]
pool_token_pairs = [
  ["0x2f295ee5dff385343675815acec5e3cbd21c64d37062e3186eec10ee983f5a73", "0x2365f7da7668d8471b387f2a6946359cd431d3ed6f5af5cf227b4d26f6277a50"],
  ["0x0", "0x0"],
  ["0x0", "0x0"],
]
