#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VERSION="$(tr -d '[:space:]' < "$ROOT/.aztec-version")"

if [ ! -d contracts ]; then
  echo "No contracts/ directory. Nothing to compile."
  exit 0
fi

for dir in contracts/*/; do
  if [ -f "$dir/Nargo.toml" ]; then
    echo "→ Compiling $dir"
    # Mount the WORKSPACE root (not just the per-contract dir) so that path-based Nargo
    # dependencies like `token = { path = "../token" }` resolve correctly inside the container.
    pkg_rel="${dir%/}"
    docker run --rm --entrypoint bash \
      -v "$ROOT:/work" -w "/work/$pkg_rel" \
      "aztecprotocol/aztec:$VERSION" \
      -c 'export PATH=/usr/src/noir/noir-repo/target/release:$PATH && node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js compile'
  fi
done

echo "All contracts compiled."

# Noir circuits (non-contract). Same docker image as contracts to keep the
# nargo binary aligned with .aztec-version. The circuit's target/ is mounted
# back via the workspace bind so the host sees the produced clearing.json.
if [ -d circuits ]; then
  for dir in circuits/*/; do
    if [ -f "$dir/Nargo.toml" ]; then
      echo "→ Compiling $dir"
      pkg_rel="${dir%/}"
      docker run --rm --entrypoint bash \
        -v "$ROOT:/work" -w "/work/$pkg_rel" \
        "aztecprotocol/aztec:$VERSION" \
        -c 'export PATH=/usr/src/noir/noir-repo/target/release:$PATH && nargo compile --silence-warnings'

      # bb write_vk produces the verification key the orderbook embeds on-chain.
      # CRITICAL ARCH MATCH: the vk MUST be generated by a bb whose BUILD matches the
      # AGGREGATOR that will produce clearing proofs (prod aggregator = amd64-linux).
      # bb builds are NOT bit-identical across arch: empirically the docker arm64-linux
      # bb (what `docker run` uses on Apple Silicon) yields vk_hash 0x04a0310e, while
      # amd64-linux (prod box 161) AND the macOS-native bb yield 0x0d66aa37. Generating
      # the vk with the arm64-linux docker bb on a Mac therefore deploys a vk the amd64
      # prod aggregator (and the PXE's bb.js) CANNOT verify against → clearing reverts
      # "Failed to verify the generated proof!". So generate the vk with the HOST bb
      # (BB_VK_BIN), which on macOS matches the amd64 prod aggregator. On an amd64 Linux
      # deploy host, point BB_VK_BIN at that host's amd64 bb (or the in-image amd64 bb).
      pkg_name="$(basename "$pkg_rel")"
      bc_path="$pkg_rel/target/$pkg_name.json"
      vk_path="$pkg_rel/target/vk.bin"
      BB_VK_BIN="${BB_VK_BIN:-$HOME/.aztec/versions/$VERSION/node_modules/@aztec/bb.js/build/arm64-macos/bb}"
      if [ -f "$ROOT/$bc_path" ]; then
        echo "→ Writing VK for $pkg_rel (host bb: $BB_VK_BIN — arch must match the prod aggregator)"
        ( cd "$ROOT" && "$BB_VK_BIN" write_vk -b "$bc_path" -o "$vk_path" -t noir-recursive )
      fi
    fi
  done
  echo "All circuits compiled + VKs written."
fi
