#!/usr/bin/env node
//
// Sub-6a A3: measure submit_order_bulk gate count + vk_hash via the `bb` CLI.
// Uses spawn (child_process.spawn) -- NOT exec -- for safety + clarity.
//
// Output: appends a timestamped block to
//         docs/superpowers/specs/sub6a-gate-measurement.md.
//
// Prerequisites:
//   - `bb` CLI installed (ships with aztec-up toolchain; verify: bb --version)
//   - `nargo compile` has produced contracts/orderbook/target/orderbook-Orderbook.json
//
// Usage: pnpm tsx scripts/measure-bulk-submit-gates.ts

import { spawn } from "node:child_process";
import {
  writeFileSync,
  existsSync,
  appendFileSync,
  mkdirSync,
} from "node:fs";
import { dirname } from "node:path";

const ORDERBOOK_TARGET =
  "contracts/orderbook/target/orderbook-Orderbook.json";
const MEASUREMENT_FILE =
  "docs/superpowers/specs/sub6a-gate-measurement.md";

function runBb(
  args: string[]
): Promise<{ stdout: string; stderr: string; code: number }> {
  return new Promise((resolve) => {
    const child = spawn("bb", args);
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d: Buffer) => {
      stdout += d.toString();
    });
    child.stderr.on("data", (d: Buffer) => {
      stderr += d.toString();
    });
    child.on("exit", (code) => resolve({ stdout, stderr, code: code ?? -1 }));
    child.on("error", (err) =>
      resolve({ stdout, stderr: `${err.message}\n${stderr}`, code: -127 })
    );
  });
}

function nargoCompile(): Promise<{ code: number; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn("nargo", ["compile"], {
      cwd: "contracts/orderbook",
    });
    let stderr = "";
    child.stderr.on("data", (d: Buffer) => {
      stderr += d.toString();
    });
    child.on("exit", (code) => resolve({ code: code ?? -1, stderr }));
    child.on("error", (err) =>
      resolve({ code: -127, stderr: `${err.message}\n${stderr}` })
    );
  });
}

async function main(): Promise<void> {
  const date = new Date().toISOString().slice(0, 19).replace("T", " ");

  console.log("Step 1: nargo compile orderbook...");
  const compile = await nargoCompile();
  if (compile.code !== 0) {
    console.error(`nargo compile failed (exit ${compile.code}):`);
    console.error(compile.stderr.slice(0, 1000));
    process.exit(1);
  }
  if (!existsSync(ORDERBOOK_TARGET)) {
    console.error(
      `Compile succeeded but target not found at ${ORDERBOOK_TARGET}`
    );
    process.exit(1);
  }
  console.log(`  ${ORDERBOOK_TARGET} produced.`);

  console.log("Step 2: bb gates submit_order_bulk...");
  // The exact bb CLI invocation varies by bb version. Common forms include:
  //   bb gates --circuit <target> --function submit_order_bulk
  //   bb prove --circuit-file <target> --function submit_order_bulk --gates-only -o /tmp/x.bin
  //   bb info --circuit <target> --function submit_order_bulk
  // Try the canonical form first; fall back to alternates if exit != 0.
  let bbOut = await runBb([
    "gates",
    "--circuit",
    ORDERBOOK_TARGET,
    "--function",
    "submit_order_bulk",
  ]);
  if (bbOut.code !== 0) {
    console.log(
      `  'bb gates --circuit ... --function ...' exited ${bbOut.code}; trying alternate form...`
    );
    bbOut = await runBb([
      "info",
      "--circuit",
      ORDERBOOK_TARGET,
      "--function",
      "submit_order_bulk",
    ]);
  }
  if (bbOut.code !== 0) {
    console.error(`bb gates/info both failed:`);
    console.error(`  stderr: ${bbOut.stderr.slice(0, 1000)}`);
    console.error(`  exit code ${bbOut.code}`);
    if (bbOut.code === -127) {
      console.error(
        `  -> bb CLI not found in PATH. Install via 'aztec-up' or check the Aztec toolchain docs.`
      );
    }
    process.exit(1);
  }

  console.log("Step 3: append to measurement file...");
  const block = `\n## Run ${date}\n\n\`\`\`\n${bbOut.stdout.trim()}\n\`\`\`\n`;
  mkdirSync(dirname(MEASUREMENT_FILE), { recursive: true });
  if (existsSync(MEASUREMENT_FILE)) {
    appendFileSync(MEASUREMENT_FILE, block);
  } else {
    const header =
      "# Sub-6a A3: submit_order_bulk gate measurement\n\n" +
      "Auto-generated by `scripts/measure-bulk-submit-gates.ts`. Each run appends a timestamped block.\n";
    writeFileSync(MEASUREMENT_FILE, header + block);
  }
  console.log(`  Wrote to ${MEASUREMENT_FILE}`);

  console.log(
    "\nDone. Manually update the Decision section per A5 if measurement N > 350,000."
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
